const menu = {
    list() {
        return [
    {
        "backMenu":[
        ],
        "frontMenu":[
        ],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    },
    {
        "backMenu":[
			{
                "child":[
                    {
						"appFrontIcon":"cuIcon-form",
                        "buttons":[
                            "查看",
                        ],
                        "menu":"公告",
                        "menuJump":"列表",
                        "tableName":"gonggao"
                    }
                ],
                "menu":"公告"
            }
			,
			{
                "child":[
                    {
						"appFrontIcon":"cuIcon-form",
                        "buttons":[
                            "查看",
                        ],
                        "menu":"疫苗",
                        "menuJump":"列表",
                        "tableName":"yimiao"
                    }
                ],
                "menu":"疫苗"
            }
            ,
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-evaluate",
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"疫苗反馈",
                        "menuJump":"列表",
                        "tableName":"yimiaoCommentback"
                    }
                ],
                "menu":"疫苗反馈"
            }
            ,
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-order",
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"疫苗订单",
                        "menuJump":"列表",
                        "tableName":"yimiaoOrder"
                    }
                ],
                "menu":"疫苗订单"
            }
        ],
        "frontMenu":[
        ],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"是",
        "hasFrontRegister":"是",
        "roleName":"用户",
        "tableName":"yonghu"
    }
]

	}
}
export default menu;
